spring.datasource.url=${mysql://root:aHEOherWhcZKFPVuQWqYAfEQAHeldgNW@switchback.proxy.rlwy.net:36036/railway}
spring.datasource.username=${root}
spring.datasource.password=${aHEOherWhcZKFPVuQWqYAfEQAHeldgNW}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
server.port=${PORT:8080}
