spring.datasource.url=jdbc:mysql://localhost:3306/medislot_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=medislot_secret_key_nanditha_2025
jwt.expiration=86400000
server.port=8080
